### ISSUE TITLE
Fix create identity error with pure digital account - [opened]

### ISSUE THREAD

**Issue by polkit-github-migration-bot** [polkit-org/polkit#343]
In gitlab.freedesktop.org by juchengshi on Aug 30, 2022, 03:25

Link to the original merge request: https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/133
This merge request consists of the following commits:
* https://github.com/polkit-org/polkit/commit/d40b2f4fd86713b1b746af2133c749390f8ff26a ("Fix create identity error with pure digital account")

**Comment by jrybar-rh** [comment]
Hello,  
Excerpt from `useradd` manpage:  
_Fully numeric usernames and usernames . or .. are also disallowed._
