### ISSUE TITLE
/usr/local/share is not supported for rules and actions

### ISSUE THREAD

**Issue by bam80** [polkit-org/polkit#419]
I see the support for rules was added once, but then reverted:
https://gitlab.freedesktop.org/polkit/polkit/-/merge_requests/77

@jrybar-rh are you going to bring it back, preferably with actions?

We at KDE are struggling without such support:
https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/1715/diffs#60cf9b542a37959697ff619f4306430348c9e7b2_38_25

Thank you.

**Comment by jrybar-rh** [comment]
Hello,  
yes, this can be looked into, since you added it into issues, once other priorities are taken care of.  
TBH, the entire code governing rules/actions-loading seems to need a little care.  
Thanks for reporting.

**Comment by jinliu** [comment]
It would be good if `/run` is also supported, in the usual precedence of `/run -> /usr/local -> /usr`. So the KDE dev session can temporarily install some rules, without affecting other, system-installed sessions.

**Comment by jrybar-rh** [comment]
Resolved by the following commits:
https://github.com/polkit-org/polkit/commit/6c5705e0d36a8b893cf2d0f888d88b0c7c19edc9 
https://github.com/polkit-org/polkit/commit/9345fd50b34827ba226cc7ff042624a7ed3abb6f  
https://github.com/polkit-org/polkit/commit/9958c259f82b066f613d171d2934c1bd829e31a4
