### ISSUE TITLE
How about the ACTUAL instructions to compile polkit with meson?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [polkit-org/polkit#420]
How about the ACTUAL instructions to compile polkit with meson?  Sorry but the following is means nothing (to me)...

```
$ meson setup [[-D option]...] target_directory
$ meson compile -C target_directory
...
# meson install -C target_directory
```
Yes I can git clone the sources but then what?  Expecting something like...
```
# git clone https://gitlab.gnome.org/GNOME/glib.git
# cd glib
# /usr/local/bin/meson setup _build
# /usr/local/bin/meson compile -C _build
# /usr/local/bin/meson install -C _build
```
At least those that created the latest glib library provided the actual steps to create the library.

**Comment by Jibun-no-Kage** [comment]
Well I think I got polkit compiled but the project that needs it cannot find it... trying to create gdm-settings application, but it fails to find polkit even though I think I was able to compile and install it?

```
# cd polkit
# /usr/local/bin/meson setup _build
# /usr/local/bin/meson compile -C _build
# /usr/local/bin/meson install -C _build
```
But I guess not?

**Comment by jrybar-rh** [comment]
Hello,

If I may suggest, the documentation to [meson build system](https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project) is extensive and well-structured, I'd start with that.  
If you need inspiration, you can observe our [CI file](https://github.com/polkit-org/polkit/blob/3cc48477a2a0e2105b646cb67d8b7eb9bf0719c9/.github/workflows/ci.sh#L43) that calls meson for testing purposes.  

> trying to create gdm-settings application, but it fails to find polkit even though I think I was able to compile and install it?

Is polkit daemon running? Are the configuration files in the expected directories (adjustable in the configuration phase of polkit build. Defaults should be ok, but that depends on your linux distro)? Why don't you use the package distributed with your linux distro? That sets everything as it should be and starts the daemon automatically.  

Good luck, have fun!
