### ISSUE TITLE
Add CI test case for polkit - systemd integration

### ISSUE THREAD

**Issue by msekletar** [polkit-org/polkit#439]
**Is your feature request related to a problem? Please describe.**
This RFE is motivated by #206.

**Describe the solution you'd like**
Simple automated test (something along the lines of reproducer from #206) for this use-case to prevent future regressions.

**Describe alternatives you've considered**
I think this functionality should be tested in upstream but in case this request can't be fulfilled for any reason I will seek solution on distribution level (Fedora).

**Additional context**
Polkit rules for systemd unit management are often used feature and it would be great to have test coverage for it in upstream CI.

**Comment by jrybar-rh** [comment]
Hello @bluca,  
Can you cover this, please?

**Comment by bluca** [comment]
There's no test infrastructure in place to do anything like that, it would be a huge task and I'm afraid I just don't have the time for that, sorry

**Comment by jrybar-rh** [comment]
Ok, from what I've seen in monitoring of dbus, it looks like the dbusmock needs to be updated to provide response for the new GetConnectionCredentials method. I'm exploring the dbusmock settings right now.

**Comment by jrybar-rh** [comment]
Fixed in [f510b3f](https://github.com/mrc0mmand/polkit/commit/f510b3fa54bd51c8de22f72ae76e0ee44faaba88)
