### ISSUE TITLE
CodeQL workflow runs getting cancelled

### ISSUE THREAD

**Issue by notpeelz** [polkit-org/polkit#467]
@mrc0mmand It seems like CodeQL workflow runs are cancelling runs from other PRs.

I force-pushed on two PR branches and this is what happened:
First force push: https://github.com/polkit-org/polkit/actions/runs/9683900802
Second force push: https://github.com/polkit-org/polkit/actions/runs/9683906482

The first one got cancelled by the second one.
![image](https://github.com/polkit-org/polkit/assets/920910/28d30f58-42ec-4d3f-a07b-1992e9b85733)

**Comment by mrc0mmand** [comment]
Ugh, sorry about that. Fix is waiting in https://github.com/polkit-org/polkit/pull/468.
