### ISSUE TITLE
You must have automake > 1.10 or 1.11 installed to compile this program.

### ISSUE THREAD

**Issue by ghost** [polkit-org/polkit#475]
**Describe the bug**
yay installation fails due automake version mismatch

**To Reproduce**
yay -Sy automake lxpolkit-git

**Desktop (please complete the following information):**
 - OS (including version): Arch 6.9.9 (amd64)
 - DE: i3wm
 - Version of polkit: `lxpolkit-git-1:0.1.0.r34.g55fc5d4-5`

**Additional context**
lxpolkit says my automake version has to be > 1.10 or 1.11 but my version is 1.17
Looking at your Source i found two checks 
```
if [ "$AM_INSTALLED_VERSION" != "1.10" \
    -a "$AM_INSTALLED_VERSION" != "1" ];then
...
``` 
But this Checks just 1.10. So i tried installing autmake from source (`https://ftp.gnu.org/gnu/automake/automake-1.10.1.tar.gz`)  but then i get `configure: error: cannot find required auxiliary files: missing install-sh`
So i tried patching `autogen.sh` to check for `1.17` That just gave me
```
./configure: line 4212: syntax error near unexpected token `0.40.0'
./configure: line 4212: `IT_PROG_INTLTOOL(0.40.0)' 
```
--**End**--
`"Linux is free if you don't value your time"`

**Comment by mbiebl** [comment]
The automake based build system has been removed a long time ago (c5c6b784221b9dc054548c15e94719c4e961a7f2) so whatever failure you have with automake is no longer relevant for polkit.
