### ISSUE TITLE
Add Slovenian (sl) as UI language

### ISSUE THREAD

**Issue by filmsi** [polkit-org/polkit#479]
Please add Slovenian (sl) as UI language and check in the attached sl po file.

The translation is provided by the official Slovenian GNOME l10n Team.

I am not a coder so I do not know where to change this in the code and how to open a pull request.

Thank you,
Martin
[sl.po.zip](https://github.com/user-attachments/files/16509819/sl.po.zip)

**Comment by filmsi** [comment]
Here is my try:
https://github.com/polkit-org/polkit/pull/481

**Comment by vmihalko** [comment]
Closed via https://github.com/polkit-org/polkit/pull/481.
