### ISSUE TITLE
Debian sid users faced with baffling choices

### ISSUE THREAD

**Issue by jidanni** [polkit-org/polkit#492]
On Debian sid there are these confusing questions:
```
The following packages have unmet dependencies:
 polkitd-pkla : Depends: libpolkit-gobject-1-0 (= 124-2) but 125-2 is to be installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     libpolkit-agent-1-0 [124-2 (now)]                  
2)     libpolkit-gobject-1-0 [124-2 (now)]                
3)     pkexec [124-2 (now)]                               
4)     polkitd [124-2 (now)]                              



Accept this solution? [Y/n/q/?] n
The following actions will resolve these dependencies:

     Remove the following packages:                       
1)     pkexec [124-2 (now)]                               
2)     policykit-1 [124-2 (now)]                          

     Keep the following packages at their current version:
3)     libpolkit-agent-1-0 [124-2 (now)]                  
4)     libpolkit-gobject-1-0 [124-2 (now)]                
5)     polkitd [124-2 (now)]                              



Accept this solution? [Y/n/q/?] n
The following actions will resolve these dependencies:

     Remove the following packages:         
1)     cros-garcon [0.30 (now, stable)]     
2)     cros-guest-tools [0.39 (now, stable)]
3)     polkitd-pkla [124-2 (now)]            
```
I must never remove cros packages, as it will break my Chromebook.

What solution should I pick?

If I pick the first solution, the question will just appear the next time.

**Comment by bluca** [comment]
Remove cros packages, as they are not part of Debian, and then rebuild them manually against the right version of the library. But anyway, this is unrelated to the upstream bug tracker of polkit.

**Comment by jidanni** [comment]
https://www.reddit.com/r/Crostini/comments/vbx7qm/comment/icbiaw4/

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1077090

So I don't know what to do.

I am just a normal user, who does not want to "rebuild" things.

**Comment by bluca** [comment]
If you aren't the owner of those cros packages, you need to report this to the owners of said packages. There is nothing that can be done here, and there is nothing that can be done in Debian either. This is purely an issue of those cros packages, and can only be solved by either you who uses them, or who provides them.

**Comment by jidanni** [comment]
OK, I made https://issues.chromium.org/issues/360265312 . Thanks.
