### ISSUE TITLE
polkit error when running systemctl suspend on sxhkd

### ISSUE THREAD

**Issue by nitrogenxx** [polkit-org/polkit#493]
### Used distribution

archlinux

### Linux kernel version used

6.6.35-2-lts

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

when I'm using the command
`$systemctl suspend` on the terminal it execute properly without any error as it should be..

but

when I'm putting this command `$systemctl suspend` in the `sxhkdrc` .. example :
`~/.config/sxhkd/sxhkdrc`
```
  super + F3
  systemctl suspend
```

and running `sxhkd` on terminal .. example :
`$sxhkd -c ~/.config/sxhkd/sxhkdrc `
then press the key `super + F3`

------------- or/and ---------------

when I'm running this command `$setsid systemctl suspend` directly on terminal 

then I'm having this error on the terminal
`Error creating textual authentication agent: Error opening current controlling terminal for the process (\/dev/tty'): No such device or address (polkit-error-quark, 0)`

however after the error my system still goes into sleep mode as it should be.

why I'm having this error when running this `$systemctl suspend` command using `sxhkd` and why I'm not having error when running this command directly on terminal ??
and
why im having same error message when running `$setsid systemctl suspend` command on terminal  ??
how to resolve the issue ?

I would greatly appreciate your help or any insight possible. pink heart emoji

**Comment by jrybar-rh** [comment]
Hello,
thanks for reporting. Can you please provide more info?
Namely:
- polkit version
- desktop environment and its version
- journal logs when sending the command (e.g. `sudo journalctl -S -1m`, i.e. the last 1 minute)

**Comment by jrybar-rh** [comment]
Inactive issue, low severity -> CLOSED
