### ISSUE TITLE
Actions not working anymore since 9958c25

### ISSUE THREAD

**Issue by seb128** [polkit-org/polkit#530]
**Describe the bug**
The change to allow reading actions for alternative actions broke the loading of symlinked actions

**To Reproduce**

On an Ubuntu Noble system with firewalld installed an a policykit-1 package with 9958c25 cherry picked

```
# firewall-cmd --list-services
ERROR:dbus.proxies:Introspect error on :1.34:/org/fedoraproject/FirewallD1: dbus.exceptions.DBusException: org.freedesktop.PolicyKit1.Error.Failed: Action org.fedoraproject.FirewallD1.info is not registered
Error: Action org.fedoraproject.FirewallD1.info is not registered

# ls -lh /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.policy
lrwxrwxrwx 1 root root 53 Jan 29  2024 /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.policy -> /etc/alternatives/org.fedoraproject.FirewallD1.policy

# pkaction --action-id=org.fedoraproject.FirewallD1.config.info
No action with action id org.fedoraproject.FirewallD1.config.info
```

**Expected behavior**

without the change

```
# firewall-cmd --list-services
dhcpv6-client ssh

# pkaction --action-id=org.fedoraproject.FirewallD1.config.info
org.fedoraproject.FirewallD1.config.info
```

**Comment by seb128** [comment]
Sorry, the report we got was about a symlink and I assumed that was the issue

**Comment by nteodosio** [comment]
It seems like memory management indeed. As a test I sent `directories` and `has_loaded_all_files` to global scope and everything then works as per my tests.

**Comment by seb128** [comment]
Sorry for the noise,  it seems a bug in our changes to apply the commit on top of v124 which is the one we have in Noble, closing

**Comment by jrybar-rh** [comment]
I know this has been closed, but I cannot but ask: why is an alternative action file symlinked to /usr/share ? `/usr/share` is, by FHS, supposed to contain immutable files vendored by the package. On the other hand we have /etc, which is supposed to contain system-specific configuration. In polkit and other services, /etc has priority over /usr/share, hence the alternative action file shall reside there, not symlinked in /usr/share.

**Comment by nteodosio** [comment]
> why is an alternative
> action file symlinked to /usr/share

It is the other way around:

  /usr/share/polkit-1/actions/org.fedoraproject.FirewallD1.policy ->
  /etc/alternatives/org.fedoraproject.FirewallD1.policy
