### ISSUE TITLE
Call to JS_Init() should be checked for failure

### ISSUE THREAD

**Issue by polkit-github-migration-bot** [polkit-org/polkit#89]
In gitlab.freedesktop.org by jslater on Aug 6, 2019, 21:02

Link to the original issue: https://gitlab.freedesktop.org/polkit/polkit/-/issues/88
If JS_Init() fails, polkit will continue and probably eventually segfault somewhere in the mozjs library because pieces of the library will not have been initialized.  This has been seen for mips64 built using poky.

**Comment by jrybar-rh** [comment]
Support for mozjs has been dropped from polkit. Many thanks to everyone involved!
